### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by kasbah**

### CODE REVIEW

**Comment by kasbah** [comment]
Looks like we'll keep older eslint?

**Comment by dvdfreitag** [comment]
Well v0.10 is only set to be supported for another month and a half by nodejs themselves. Perhaps it's time to start moving towards v4/v6 support?

https://github.com/nodejs/LTS

**Comment by mcous** [comment]
Yeah, sorry for the ugly red devDeps badge, but I have been holding off on the eslint update until 0.10/0.12 support is officially dropped at the end of the year. No sense dropping CI testing for a legitimate platform just because there's an update to the linting tool

**Comment by kasbah** [comment]
I've restricted this to just update Mocha.

**Comment by mcous** [comment]
Cool! I'm gonna push a couple more build updates to this branch and then merge

**Pull request merged**
